### ISSUE TITLE
Comments in the source code

### ISSUE THREAD

**Issue by Kait0** [litespeedtech/lsquic-client#22] opened 2018-05-02 17:19 UTC
Now I know this is not neccessarily an issue but one thing that makes it challenging to work with the source code is the lack of comments within it.  Without comments you often have to reengineer the code yourself find out what functions do and how they are supposed to be used which can become a rabbithole quickly if these functions than call a bunch of other functions.

I might help out with this once I have a proper understanding of the code but right now I am mostly guessing what functions do.

Since I don't think it deserves an own thread I'll put it here. In line 332 http_client.c somebody forgot to remove some debug code I think: 
`#ifndef NDEBUG
                const int s =
#endif`

I also have a question that I don't know where to ask so I'll put it here.
Is there (and where :) ) some kind of data structure that stores the server response and meta infos like quic version used etc. that I can access from the main function?

**Comment by dtikhonov** [comment] 2018-05-02 17:51
Part A
------

> Now I know this is not neccessarily an issue but one thing that makes it challenging to work with the source code is the lack of comments within it. Without comments you often have to reengineer the code yourself find out what functions do and how they are supposed to be used which can become a rabbithole quickly if these functions than call a bunch of other functions.
> 
> I might help out with this once I have a proper understanding of the code but right now I am mostly guessing what functions do.

The public functions are documented in [lsquic.h](../tree/master/include/lsquic.h).  The library's internals are always subject to change without notice, so the code is its own comments.  We are not really _against_ comments, however: which functions do you think need better comments?

Part B
------
The code in http_client.c (snippet below) checks that setting of priority was successful, but only when assertions are enabled, which is true when symbol `NDEBUG` is undefined.

```
#ifndef NDEBUG
                const int s =
#endif
                lsquic_stream_set_priority(stream, new_prio);
                assert(s == 0);
```

Part C
------
Use functions from [lsquic.h](../tree/master/include/lsquic.h) to get information about the connection: `lsquic_conn_quic_version()` (I actually see that this one is missing -- I'll fix it), `lsquic_conn_status()`, `lsquic_conn_id()`, and a few others.

Not everything in `struct lsquic_conn` and `struct full_conn` are exposed.  If you would need something from those structs, we could add a public function.  What do you need?

**Comment by dtikhonov** [comment] 2018-05-02 17:58
> `lsquic_conn_quic_version()` (I actually see that this one is missing -- I'll fix it)

Addressed in 881272b.

**Comment by Kait0** [comment] 2018-05-02 18:58
Thanks for the quick response and fix.
Part A
I was talking about the client so proc.c/h and htt_client.c 

Part B
My bad I overlooked that the statement continues 2 lines below.

Part C
Used tls and http version would be interesting and wether the connection succeded or failed.

**Comment by dtikhonov** [comment] 2018-05-03 15:37
I see.  The client is just an example how the library is to be used, it's not the product, so to speak.  Which parts are not clear, specifically?  We will add comments for those.

The HTTP version used is really HTTP over QUIC, or HQ.  It is neither HTTP/2 nor HTTP/1.x, although it is closer to HTTP/2.  I believe we discussed this in issue #21.  As for TLS: only the QUIC Crypto is used for now.  Once IETF QUIC is implemented, it will be either QUIC Crypto or TLS1.3.

**Comment by Kait0** [comment] 2018-05-04 14:19
I have trouble understanding how the client handles and where it stores the server response
I know it happens in `s = prog_run(&prog);`
which calls `event_base_loop(prog->prog_eb, 0);` and gives it a bunch of parameters.
I assume those are functions that than handle the server response when it arrives but I don't know which are these functions and how I can access the server resonse from outside.

**Comment by dtikhonov** [comment] 2018-05-04 18:12
The functions in `prog.c` are just handlers for the event loop.  In the case of our test program, http_client, the event loop is libevent.  lsquic-client does not depend on any particular event loop.

The critical piece of code in http_client.c is this:
```
const struct lsquic_stream_if http_client_if = {
    .on_new_conn            = http_client_on_new_conn,
    .on_conn_closed         = http_client_on_conn_closed,
    .on_new_stream          = http_client_on_new_stream,
    .on_read                = http_client_on_read,
    .on_write               = http_client_on_write,
    .on_close               = http_client_on_close,
};
```

This structure (part of the public API in lsquic.h) specifies the callback that are used when connection is created and terminated, as well as stream handling.  Each QUIC stream corresponds to an HTTP request/response pair.  The client sends the request in `http_client_on_write()` callback and processes the response in `http_client_on_read()` callback.

**Comment by Kait0** [comment] 2018-05-16 19:18
Mind if I use this thread to ask small questions?
In lsquic.h
```
enum lsquic_version
{
     ...

    /**
     * Q043.  Support for processing PRIORITY frames.  Since this library
     * has supported PRIORITY frames from the beginning, this version is
     * exactly the same as LSQVER_042.
     */
    LSQVER_043,

    N_LSQVER
};
```
what does N_LSQVER stand for?
I get that as return (or rather 3) when I use 
```
lsquic_conn_t *conn = lsquic_stream_conn(stream);
enum lsquic_version version = lsquic_conn_quic_version(conn);
```
in http_client_on_close()

**Comment by dtikhonov** [comment] 2018-05-16 19:34
You should not get that value back.  I cannot reproduce it here -- how did you do it?

**Comment by dtikhonov** [comment] 2018-05-16 19:34
`N_LSQVER` is just the count of preceding values in the enum.

**Comment by Kait0** [comment] 2018-05-16 19:42
```
static void
http_client_on_close (lsquic_stream_t *stream, lsquic_stream_ctx_t *st_h)
{
    const int pushed = lsquic_stream_is_pushed(stream);
    if (pushed)
    {
        assert(NULL == st_h);
        return;
    }

    LSQ_INFO("%s called", __func__);
    lsquic_conn_t *conn = lsquic_stream_conn(stream);
    lsquic_conn_ctx_t *conn_h;

    enum lsquic_version version = lsquic_conn_quic_version(conn);
```
Rest of the function stays the same
Arguments are -H www.google.com -s 443 -p /

**Comment by dtikhonov** [comment] 2018-05-16 21:10
Cannot reproduce:

```
[dmitri@ubuntu-dmitri lsquic-client]$ git log --oneline | head -1
07354a9 DNS resolution: can specify hostname via -H or -s
[dmitri@ubuntu-dmitri lsquic-client]$ git diff
diff --git a/test/http_client.c b/test/http_client.c
index 1cbae58..67b452c 100644
--- a/test/http_client.c
+++ b/test/http_client.c
@@ -372,6 +372,7 @@ http_client_on_close (lsquic_stream_t *stream, lsquic_stream_ctx_t *st_h)

     LSQ_INFO("%s called", __func__);
     lsquic_conn_t *conn = lsquic_stream_conn(stream);
+    LSQ_WARN("QUIC version: %d", lsquic_conn_quic_version(conn));
     lsquic_conn_ctx_t *conn_h;
     TAILQ_FOREACH(conn_h, &st_h->client_ctx->conn_ctxs, next_ch)
         if (conn_h->conn == conn)
[dmitri@ubuntu-dmitri lsquic-client]$ ./http_client -s www.google.com -p / -K
17:09:35.208 [WARN] QUIC version: 2
[dmitri@ubuntu-dmitri lsquic-client]$
```

Are you using the latest code?

**Comment by dtikhonov** [comment] 2018-05-17 19:17
Oh.  I guess Windows does not have `<regex.h>`.  Hmm...  And I was very happy with myself yesterday. 😄

**Comment by Kait0** [comment] 2018-05-18 12:12
```
enum lsquic_version version = lsquic_conn_quic_version(conn);
```
I tested it in linux and it returned the correct value (2). So ether this is a Windows only problem or was fixed in the latest commit. I would guess the former.

**Comment by dtikhonov** [comment] 2018-05-18 13:33
> The newest commit doesn't work in windows

Should be fixed now.

**Comment by Kait0** [comment] 2018-05-18 13:40
I can confirm that its fixed

**Comment by Kait0** [comment] 2018-05-18 13:41
lsquic_conn_quic_version() also returns the correct value now

**Comment by Kait0** [comment] 2018-05-18 14:28
```
        case '4':
            prog.prog_ipver = 4;
            break;
        case '6':
            prog.prog_ipver = 4;
            break;
```
A bug in http_client

**Comment by dtikhonov** [comment] 2018-05-18 14:31
> A bug in http_client

Thank you.

**Comment by dtikhonov** [comment] 2018-05-18 14:39
`-6` has been fixed.

**Comment by Kait0** [comment] 2018-05-18 14:47
![grafik](https://user-images.githubusercontent.com/4252687/40241322-01898220-5abb-11e8-9323-7c85358d33e3.png)
something broke with the latest changes commit I think

**Comment by Kait0** [comment] 2018-05-18 14:51
you included "test_config.h" which is not a versioned file. I think it's related to that.

**Comment by dtikhonov** [comment] 2018-05-18 15:01
This file gets generated when cmake is run.

**Comment by Kait0** [comment] 2018-05-18 15:02
where is SPORT_DONT_FRAGMENT supposed to be defined?

**Comment by Kait0** [comment] 2018-05-18 15:16
![grafik](https://user-images.githubusercontent.com/4252687/40242682-8c969184-5abe-11e8-8496-7ec235f9f6f0.png)
To answer my own question its supposed to be defined in test_common.h if LSQUIC_DONTFRAG_SUPPORTED which on my system (windows) is not true.

which is defined in test_config.h which looks like this for me.
```
#ifndef LSQUIC_CONFIG_H
#define LSQUIC_CONFIG_H

/* #undef HAVE_IP_DONTFRAG */
/* #undef HAVE_IP_MTU_DISCOVER */
/* #undef HAVE_REGEX */

#define LSQUIC_DONTFRAG_SUPPORTED (HAVE_IP_DONTFRAG || HAVE_IP_MTU_DISCOVER)

#endif
```

hope this helps

**Comment by dtikhonov** [comment] 2018-05-18 15:58
Thanks -- we made a fix, please pull.

**Comment by Kait0** [comment] 2018-05-18 16:29
works. Thank you

**Comment by Kait0** [comment] 2018-05-21 14:04
So I am trying to measure the time it takes to establish a quic connection (to compare it with tcp).
In lsquic the initial connection establishment happens in lsquic_engine_connect() if I am not wrong.
Would measuring the time this function takes give an accurate pictures of how long it takes to establish a quic connection or does this function also do other stuff that would distort the result?

**Comment by dtikhonov** [comment] 2018-05-21 18:28
No, this is not accurate, as this function returns before the handshake completes.

Your question exposes a deficiency in the API: there is no "on handshake successful" callback.  `on_new_conn()` called as soon as the connection instance is created, but it is not the same thing as having a working connection.

**Comment by dtikhonov** [comment] 2018-05-21 19:04
Check out the new `on_hsk_done()` callback in c44946e.

**Comment by Kait0** [comment] 2018-05-22 11:51
awesome.
I do get a warning in the with latest commit.
![image](https://user-images.githubusercontent.com/4252687/40360696-3f180ec2-5dc7-11e8-96af-2e71d6e9948f.png)

**Comment by dtikhonov** [comment] 2018-05-22 12:56
This is a bogus warning: you can ignore it.  I will add an explicit initialization to quiet MSVC in a future commit.

**Comment by Kait0** [comment] 2018-05-23 11:15
I tested the example http_client_on_hsk_done() in http_client.c of on_hsk_done and it never gets called. Do I need to tell the library that I want to use this optional callback other than having it in the lsquic_stream_if struct?

**Comment by Kait0** [comment] 2018-05-23 15:35
Thanks that helped. I had to clean the entire project and rebuild it to make it work.

**Comment by Kait0** [comment] 2018-05-23 16:37
as I mentioned earlier I am working on measuring quic connection establishment time. As that feature is just an extension of the test client would you like me to do a pull request?

**Comment by dtikhonov** [comment] 2018-05-23 17:37
This feature seems to be of limited use -- unlike, for instance, DNS resolution.  I don't think it's necessary, thanks!

**Closed** 2018-08-16 12:01 UTC
Labels: question
